### ISSUE TITLE
Remove hardcoded number of primary inputs in the aggregator circuit

### ISSUE THREAD

**Issue by AntoineRondelet** [clearmatics/zecale#8]

**Comment by AntoineRondelet** [comment]
Related to #5

**Comment by AntoineRondelet** [comment]
Also related to this thread: https://github.com/clearmatics/zecale/pull/39#discussion_r494890322

**Comment by dtebbs** [comment]
Can this issue be closed since we now assume applications will use the GGPR trick?

**Comment by AntoineRondelet** [comment]
> Can this issue be closed since we now assume applications will use the GGPR trick?

This was fixed in https://github.com/clearmatics/zecale/pull/64 - so this ticket can indeed be closed now, thanks.
(@dtebbs please make sure to link to any relevant open issue when opening a new PR, so that we can know when to close a given ticket :) )
